# Generated by Django 3.0.7 on 2020-10-24 05:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201024_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 24, 5, 39, 16, 551556, tzinfo=utc)),
        ),
    ]
